CREATE TABLE IF NOT EXISTS MEET (
	ID INTEGER AUTO_INCREMENT NOT NULL, 
	date DATE, 
	description VARCHAR(255), 
	PRIMARY KEY (ID)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS COMPETITOR (
	ID INTEGER AUTO_INCREMENT NOT NULL, 
	category VARCHAR(255), 
	name VARCHAR(255), 
	number VARCHAR(255), 
	team VARCHAR(255), 
	PRIMARY KEY (ID)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS TEAM (
	ID INTEGER AUTO_INCREMENT NOT NULL, 
	name VARCHAR(255) UNIQUE, 
	PRIMARY KEY (ID)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS meet_TEAMS (
	meet_ID INTEGER, 
	TEAMS VARCHAR(255),
	CONSTRAINT FK_meet_TEAMS_meet_ID FOREIGN KEY (meet_ID) REFERENCES MEET (ID)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS MEET_COMPETITOR (
	meet_ID INTEGER NOT NULL, 
	competitors_ID INTEGER NOT NULL, 
	PRIMARY KEY (meet_ID, competitors_ID),
	CONSTRAINT FK_MEET_COMPETITOR_meet_ID FOREIGN KEY (meet_ID) REFERENCES MEET (ID),
	CONSTRAINT FK_MEET_COMPETITOR_competitors_ID FOREIGN KEY (competitors_ID) REFERENCES COMPETITOR (ID)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS competitor_COMPETITORRESULTS (
	competitor_ID INTEGER, 
	COMPETITORRESULTS DOUBLE, 
	COMPETITORRESULTS_KEY INTEGER,
	CONSTRAINT FK_competitor_COMPETITORRESULTS_competitor_ID FOREIGN KEY (competitor_ID) REFERENCES COMPETITOR (ID)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS TEAM_MEMBER (
	number VARCHAR(255) NOT NULL, 
	category VARCHAR(255), 
	name VARCHAR(255), 
	PRIMARY KEY (number)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS TEAM_TEAM_MEMBER (
	TEAM_ID INTEGER NOT NULL, 
	members_number VARCHAR(255) NOT NULL, 
	PRIMARY KEY (TEAM_ID, members_number),
	CONSTRAINT FK_TEAM_TEAM_MEMBER_members_number FOREIGN KEY (members_number) REFERENCES TEAM_MEMBER (number),
	CONSTRAINT FK_TEAM_TEAM_MEMBER_TEAM_ID FOREIGN KEY (TEAM_ID) REFERENCES TEAM (ID)
) ENGINE=InnoDB;
