DROP TABLE meet_TEAMS;
DROP TABLE MEET_COMPETITOR;
DROP TABLE competitor_COMPETITORRESULTS;
DROP TABLE TEAM_TEAM_MEMBER;
DROP TABLE TEAM_MEMBER;
DROP TABLE TEAM;
DROP TABLE COMPETITOR;
DROP TABLE MEET;
